require "compiler/crystal/syntax"
require "./catalyst/version"
require "./catalyst/config"
require "./catalyst/rules/base"

# Auto-generated by `scripts/generate_rules_require.cr`
{{ run("../scripts/generate_rules_require.cr") }}
require "./catalyst/baseline"
require "./catalyst/visitors/base"
require "./catalyst/formatters/base"
require "./catalyst/formatters/terminal"
require "./catalyst/formatters/json"
require "./catalyst/runner"
require "./cli"

# # Static performance analysis tool for Crystal.
##
# # Detects performance anti-patterns via AST traversal
# # using the built-in `Crystal::Parser`.
module Catalyst
end

{% unless parse_type("Spec").resolve? %}
  # Act as the CLI entrypoint only when this file is the program being run
  # (built `catalyst` binary, including `catalyst.exe`, or
  # `crystal run src/catalyst.cr`). When required from other programs
  # (generate_docs, custom tooling) preserve the old call-and-ignore
  # behavior so their own entrypoints keep working.
  entry = File.basename(PROGRAM_NAME, File.extname(PROGRAM_NAME))
  if entry.ends_with?("catalyst") || entry.starts_with?("crystal-run-catalyst")
    exit(Catalyst::CLI.run(ARGV))
  else
    Catalyst::CLI.run(ARGV)
  end
{% else %}
  # Required from specs: run without exiting so `crystal spec` keeps working.
  Catalyst::CLI.run(ARGV)
{% end %}
