require "compiler/crystal/syntax"
require "./catalyst/version"
require "./catalyst/config"
require "./catalyst/rules/base"

# Auto-generated by `scripts/generate_rules_require.cr`
{{ run("../scripts/generate_rules_require.cr") }}
require "./catalyst/visitors/base"
require "./catalyst/formatters/base"
require "./catalyst/formatters/terminal"
require "./catalyst/formatters/json"
require "./catalyst/runner"
require "./cli"

# # Static performance analysis tool for Crystal.
##
# # Detects performance anti-patterns via AST traversal
# # using the built-in `Crystal::Parser`.
module Catalyst
end

{% unless parse_type("Spec").resolve? %}
  # Exit with the CLI status code when built as a binary.
  # Skipped when required from specs so `crystal spec` keeps working.
  exit(Catalyst::CLI.run(ARGV))
{% else %}
  Catalyst::CLI.run(ARGV)
{% end %}
